version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
  - package-ecosystem: 'npm'
    directory: '/packages/cli'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
  - package-ecosystem: 'npm'
    directory: '/packages/core'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
  - package-ecosystem: 'npm'
    directory: '/packages/claude-code-plugin'
    schedule:
      interval: 'weekly'
      day: 'thursday'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
